import streamlit as st
import google.generativeai as genai

st.set_page_config(page_title="Music Chatbot", page_icon="", layout="wide")

key = st.secrets["key"]

genai.configure(api_key = key)

st.title("Travel Music")
st.markdown("This is your one-stop shop for understanding the music taste in the countries you're traveling to!")
model = genai.GenerativeModel("gemini-3-flash-preview")

country = st.selectbox("What country are you visiting?", [
    "AFGHANISTAN", "ALBANIA", "ALGERIA", "AMERICAN SAMOA", "ANDORRA","ANGOLA","ANGUILLA","ARGENTINA","ARMENIA",	"ARUBA","AUSTRALIA","AUSTRIA","AZERBAIJAN","BAHAMAS","BAHRAIN","BANGLADESH","BARBADOS","BELARUS","BELGIUM","BELIZE","BENIN","BERMUDA","BHUTAN",	"BOLIVIA, PLURINATIONAL STATE OF","BOSNIA AND HERZEGOVINA","BOTSWANA","BRAZIL","BRUNEI DARUSSALAM",	"BULGARIA","BURKINA FASO","BURUNDI","CAMBODIA","CAMEROON","CANADA","CABO VERDE","CENTRAL AFRICAN REPUBLIC","CHAD","CHILE","CHINA","COLOMBIA","COMOROS","CONGO","CONGO, THE DEMOCRATIC REPUBLIC OF THE","COOK ISLANDS","COSTA RICA","CROATIA","CUBA","CYPRUS","CZECHIA","DENMARK","DJIBOUTI","DOMINICA","DOMINICAN REPUBLIC","ECUADOR","EGYPT","EL SALVADOR","EQUATORIAL GUINEA","ERITREA","ESTONIA","ETHIOPIA","FALKLAND ISLANDS (MALVINAS)","FAROE ISLANDS","FIJI","FINLAND","FRANCE","GABON","GAMBIA","GEORGIA","GERMANY","GHANA","GIBRALTAR","GREECE","GREENLAND","GRENADA","GUAM","GUATEMALA","GUINEA","GUINEA-BISSAU","GUYANA","HAITI","HONDURAS","HONG KONG","HUNGARY","ICELAND","INDIA","INDONESIA","IRAN, ISLAMIC REPUBLIC OF","IRAQ","IRELAND","ISRAEL","ITALY","JAMAICA","JAPAN","JORDAN","KAZAKHSTAN","KENYA","KIRIBATI","KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF","KOREA, REPUBLIC OF","KUWAIT","KYRGYZSTAN","LAO PEOPLE'S DEMOCRATIC REPUBLIC","LATVIA","LEBANON","LESOTHO","LIBERIA","LIBYA","LIECHTENSTEIN","LITHUANIA","LUXEMBOURG",	"MADAGASCAR","MALAWI","MALAYSIA","MALDIVES","MALI","MALTA","MARSHALL ISLANDS","MAURITANIA","MAURITIUS",	"MEXICO","MICRONESIA, FEDERATED STATES OF","MOLDOVA, REPUBLIC OF","MONACO","MONGOLIA","MONTENEGRO","MOROCCO","MOZAMBIQUE","MYANMAR","NAMIBIA","NAURU","NEPAL","NETHERLANDS","NEW ZEALAND","NICARAGUA","NIGER","NIGERIA","NORWAY","OMAN","PAKISTAN","PALAU","PALESTINE, STATE OF","PANAMA","PAPUA NEW GUINEA","PARAGUAY","PERU","PHILIPPINES","POLAND","PORTUGAL","PUERTO RICO","QATAR","ROMANIA","RUSSIAN FEDERATION","RWANDA","SAINT KITTS AND NEVIS","SAINT LUCIA","SAINT VINCENT AND THE GRENADINES","SAMOA","SAN MARINO","SAO TOME AND PRINCIPE","SAUDI ARABIA","SENEGAL","SERBIA","SEYCHELLES","SIERRA LEONE","SINGAPORE","SLOVAKIA","SLOVENIA","SOLOMON ISLANDS","SOMALIA","SOUTH AFRICA","SPAIN","SRI LANKA","SUDAN","SURINAME","SWAZILAND","SWEDEN","SWITZERLAND","SYRIAN ARAB REPUBLIC","TAJIKISTAN","TANZANIA, UNITED REPUBLIC OF","THAILAND","TIMOR-LESTE","TOGO","TONGA","TRINIDAD AND TOBAGO","TUNISIA","TURKEY","TURKMENISTAN","TUVALU","UGANDA","UKRAINE","UNITED ARAB EMIRATES","UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND","UNITED STATES OF AMERICA","URUGUAY","UZBEKISTAN","VANUATU","VENEZUELA, BOLIVARIAN REPUBLIC OF","VIET NAM","WESTERN SAHARA","YEMEN","ZAMBIA","ZIMBABWE"
], index=None)
genre = st.selectbox("What genre of music do you enjoy?", [], index=None)

try:
    response = model.generate_content(f"Write ab") #enter your prompt here!
    st.write(response.text)

except Exception as e:
    error_message = str(e).lower()

    if "quota" in error_message or "rate" in error_message or "429" in error_message:
        assistant_reply = f"FULL ERROR: {e}"
    elif "safety" in error_message or "blocked" in error_message:
        assistant_reply = "Error. I can't respond to that topic. Try asking me something else about music!"
    else:
        assistant_reply = f"Error. Something went wrong. Please try again. (Error: {str(e)})"

    with st.chat_message("assistant"):
        st.markdown(assistant_reply)
